apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-sample-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'http://gitlab.mycompany.com/group/project.git'
    path: k8s
    targetRevision: HEAD
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: web-apps
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
