apiVersion: v1
kind: Service
metadata:
  name: my-sample-app
  namespace: web-apps
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30080
  selector:
    app: my-sample-app
